### ISSUE TITLE
LESS version

### ISSUE THREAD

**Issue by Blinkers** [gudh/ihover#2]
This is possible to have a less version ?

Thanks

**Comment by gudh** [comment]
@Blinkers, thanks for the advice.

While it's easy to convert Sass to Less, it takes some extra work to add all the vendor prefix, since Sass has [Bourbon](http://bourbon.io/) to take care of that, Less hasn't (I could be wrong, let me know)

**Comment by KingYes** [comment]
You can use with https://github.com/ai/autoprefixer/ (it's have grunt version atm) for vendor prefix ! :)

**Comment by gudh** [comment]
As Bootstrap 4 uses Sass, I am gonna closed it.

Thanks for the advice!
